//! Installed ASP skill rendering for `asp hook install`.

use agent_semantic_hook::{
    ActivatedProviderConfig, HookActivation, RuntimeProfiles, RuntimeProviderProfile,
};
use std::fs;
use std::path::{Path, PathBuf};

const AGENT_SEMANTIC_PROTOCOLS_SKILL_MD: &str = include_str!("../../../../SKILL.md");

pub(super) fn install_agent_semantic_protocols_skill(
    project_root: &Path,
    activation: &HookActivation,
    runtime_profiles: &RuntimeProfiles,
) -> Result<PathBuf, String> {
    let skill_path = default_agent_skill_path(project_root);
    if let Some(parent) = skill_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    let rendered_skill = render_agent_semantic_protocols_skill(activation, runtime_profiles);
    fs::write(&skill_path, format!("{}\n", rendered_skill.trim_end()))
        .map_err(|error| format!("failed to write {}: {error}", skill_path.display()))?;
    Ok(skill_path)
}

fn default_agent_skill_path(project_root: &Path) -> PathBuf {
    project_root
        .join(".agents")
        .join("skills")
        .join("agent-semantic-protocols")
        .join("SKILL.md")
}

fn render_agent_semantic_protocols_skill(
    activation: &HookActivation,
    runtime_profiles: &RuntimeProfiles,
) -> String {
    AGENT_SEMANTIC_PROTOCOLS_SKILL_MD
        .replace(
            "<!-- ASP_INSTALLED_SKILL_NOTICE -->",
            installed_skill_notice(),
        )
        .replace(
            "<!-- ASP_PROVIDER_SUMMARY -->",
            &installed_provider_summary(activation, runtime_profiles),
        )
}

fn installed_skill_notice() -> &'static str {
    "> [!IMPORTANT]\n> Generated by `asp hook install` from the repository root `SKILL.md` template and the current provider activation. Do not edit this installed copy. Edit root `SKILL.md` or `asp.toml`, then rerun `asp hook install --client <client> .`."
}

fn installed_provider_summary(
    activation: &HookActivation,
    runtime_profiles: &RuntimeProfiles,
) -> String {
    let mut lines = vec![
        "## Active Providers".to_string(),
        String::new(),
        "Detected from provider binaries plus `asp.toml`; only activated languages are listed."
            .to_string(),
        String::new(),
        "| Language | Facade | Provider | Execution | Command |".to_string(),
        "| --- | --- | --- | --- | --- |".to_string(),
    ];
    for provider in &activation.providers {
        let runtime_provider = runtime_profiles.providers.iter().find(|profile| {
            profile.manifest_id == provider.manifest_id
                && profile.language_id == provider.language_id
                && profile.provider_id == provider.provider_id
        });
        lines.push(format!(
            "| {} | `{}` | {} | {} | `{}` |",
            markdown_table_cell(&provider.language_id),
            markdown_table_cell(&format!("asp {}", provider.language_id)),
            markdown_table_cell(&provider.provider_id),
            provider.execution.as_str(),
            markdown_table_cell(&provider_command_display(
                &activation.project_root,
                provider,
                runtime_provider,
            )),
        ));
    }
    lines.join("\n")
}

fn provider_command_display(
    project_root: &str,
    provider: &ActivatedProviderConfig,
    runtime_provider: Option<&RuntimeProviderProfile>,
) -> String {
    let argv = runtime_provider
        .and_then(runtime_provider_command_argv)
        .or_else(|| {
            if provider.provider_command_prefix.is_empty() {
                None
            } else {
                Some(provider.provider_command_prefix.clone())
            }
        })
        .unwrap_or_else(|| vec![provider_display_binary(project_root, &provider.binary)]);
    argv.iter()
        .map(|arg| {
            shell_display_word(&installed_skill_display_arg(
                project_root,
                &provider.binary,
                arg,
            ))
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn runtime_provider_command_argv(profile: &RuntimeProviderProfile) -> Option<Vec<String>> {
    if !profile.argv.is_empty() {
        return Some(profile.argv.clone());
    }
    profile
        .resolved_binary
        .as_ref()
        .map(|binary| vec![binary.clone()])
}

fn provider_display_binary(project_root: &str, binary: &str) -> String {
    let project_bin = Path::new(project_root).join(".bin").join(binary);
    if project_bin.is_file() {
        return format!(".bin/{binary}");
    }
    Path::new(binary)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(binary)
        .to_string()
}

fn installed_skill_display_arg(project_root: &str, provider_binary: &str, arg: &str) -> String {
    let path = Path::new(arg);
    if !path.is_absolute() {
        return arg.to_string();
    }
    let project_bin = Path::new(project_root).join(".bin").join(provider_binary);
    if project_bin.is_file()
        && path.file_name().and_then(|name| name.to_str()) == Some(provider_binary)
    {
        return format!(".bin/{provider_binary}");
    }
    if let Ok(relative) = path.strip_prefix(project_root) {
        return relative.to_string_lossy().replace('\\', "/");
    }
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(arg)
        .to_string()
}

fn shell_display_word(arg: &str) -> String {
    if arg
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.' | '/' | ':' | '='))
    {
        return arg.to_string();
    }
    format!("'{}'", arg.replace('\'', "'\\''"))
}

fn markdown_table_cell(value: &str) -> String {
    value.replace('|', "\\|")
}
